name: Deploy CI
on:
  push:
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      GH_TOKEN: {{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Installers for Windows & Linux
        run: |
          ENVS=`env | grep -iE '(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
          docker run $ENVS --rm \
            -v ${PWD}:/project \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "node -v && npm ci && npm run cilinux"
  mac:
    runs-on: macos-latest
    env:
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      CSC_IDENTITY_AUTO_DISCOVERY: false
      GH_TOKEN: {{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Installer for Mac
        run: npm run cidarwin
